### ISSUE TITLE
Tutorial bug [bug]

### ISSUE THREAD

**Issue by marcelladane** [bactopia/bactopia#142]
Hello guys, I am trying to run the tutorial to check if the installation was correct (and while I am waiting for the real data to run on it). 

First, I noticed that if I don´t specify "--outdir" here it doesn´t work:
bactopia datasets datasets/ --ariba "vfdb_core,card" \
                            --species "Staphylococcus aureus" \
                            --include_genus \
                            --cpus 4
It is not a big deal, but since it is a tutorial, I thought you would like to add the info needed to run it easily....

But my other problem is more serious. I can´t run your dataset, I get the following error: 
 Bactopia Execution Summary
    ---------------------------
    Command Line    : nextflow run /home/marcellap/miniconda3/envs/bactopia//share/bactopia-1.4.x/main.nf --accession SRX4563634 --datasets bactopia-tutorial/datasets/ --species 'Staphylococcus aureus' --coverage 100 --genome_size median --cpus 2 --outdir ena-single-sample
    Resumed         : false

    Completed At    : 2020-10-08T21:23:50.420595+02:00
    Duration        : 1h 16m 4s
    Success         : false
    Exit Code       : 1
    Error Report    : Error executing process > 'call_variants (SRX4563634 - GCF_000009645)'

Caused by:
  Process `call_variants (SRX4563634 - GCF_000009645)` terminated with an error exit status (1)

Command executed [/home/marcellap/miniconda3/envs/bactopia/share/bactopia-1.4.x/templates/call_variants.sh]:

  #!/bin/bash
  set -e
  set -u

  LOG_DIR="call_variants"
  if [ "false" == "true" ]; then
      mkdir GCF_000009645
      touch GCF_000009645/call_variants.dry_run.txt
  else
      mkdir -p ${LOG_DIR}
      echo "# Timestamp" > ${LOG_DIR}/call_variants.versions
      date --iso-8601=seconds >> ${LOG_DIR}/call_variants.versions
      echo "# Snippy Version" >> ${LOG_DIR}/call_variants.versions
      snippy --version >> ${LOG_DIR}/call_variants.versions 2>&1

      snippy --R1 SRX4563634_R1.fastq.gz --R2 SRX4563634_R2.fastq.gz \
          --ref GCF_000009645.gbff \
          --cpus 2 \
          --ram 15.8 \
          --outdir GCF_000009645 \
          --prefix SRX4563634 \
          --mapqual 60 \
          --basequal 13 \
          --mincov 10 \
          --minfrac 0 \
          --minqual 100 \
          --maxsoft 10   > ${LOG_DIR}/snippy.out 2> ${LOG_DIR}/snippy.err

      # Add GenBank annotations
      echo "# vcf-annotator Version" >> ${LOG_DIR}/call_variants.versions
      vcf-annotator --version >> ${LOG_DIR}/call_variants.versions 2>&1
      vcf-annotator GCF_000009645/SRX4563634.vcf GCF_000009645.gbff > GCF_000009645/SRX4563634.annotated.vcf 2> ${LOG_DIR}/vcf-annotator.err

      # Get per-base coverage
      echo "# bedtools Version" >> ${LOG_DIR}/call_variants.versions
      bedtools --version >> ${LOG_DIR}/call_variants.versions 2>&1
      grep "^##contig" GCF_000009645/SRX4563634.vcf > GCF_000009645/SRX4563634.full-coverage.txt
      genomeCoverageBed -ibam GCF_000009645/SRX4563634.bam -d >> GCF_000009645/SRX4563634.full-coverage.txt 2> ${LOG_DIR}/genomeCoverageBed.err
      cleanup-coverage.py GCF_000009645/SRX4563634.full-coverage.txt > GCF_000009645/SRX4563634.coverage.txt
      rm GCF_000009645/SRX4563634.full-coverage.txt

      # Mask low coverage regions
      mask-consensus.py SRX4563634 GCF_000009645 \
                        GCF_000009645/SRX4563634.consensus.subs.fa \
                        GCF_000009645/SRX4563634.subs.vcf \
                        GCF_000009645/SRX4563634.coverage.txt \
                        --mincov 10 > GCF_000009645/SRX4563634.consensus.subs.masked.fa 2> ${LOG_DIR}/mask-consensus.err

      # Clean Up
      rm -rf GCF_000009645/reference GCF_000009645/ref.fa* GCF_000009645/SRX4563634.vcf.gz*

      if [[ false == "true" ]]; then
          find GCF_000009645/ -type f -not -name "*.bam*" -and -not -name "*.log*" -and -not -name "*.txt*" | \
              xargs -I {} pigz -n --best -p 2 {}
          pigz -n --best -p 2 GCF_000009645/SRX4563634.coverage.txt
      fi

      if [ "false" == "false" ]; then
          cp .command.err ${LOG_DIR}/call_variants.err
          cp .command.out ${LOG_DIR}/call_variants.out
          cp .command.sh ${LOG_DIR}/call_variants.sh || :
          cp .command.trace ${LOG_DIR}/call_variants.trace || :
      else
          rm -rf ${LOG_DIR}/
      fi
  fi

Command exit status:
  1

Command output:
  (empty)

Work dir:
  /home/marcellap/bactopia/work/a7/52dfddabf599066865ba4eaf067a98

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line

    Launch Dir      : /home/marcellap/bactopia
    Working Dir     : /home/marcellap/bactopia/work (Total Size: 11.53G)
    Working Dir Size: 11.53G

WARN: Killing pending tasks (1)

I am using Linux subsystem in windows 10 and installed the package using conda. 

Can you please give me an idea for the possible source of problem?

**Comment by rpetit3** [comment]
Hi @marcelladane 

```
bactopia datasets datasets/ --ariba "vfdb_core,card"
--species "Staphylococcus aureus"
--include_genus
--cpus 4
```
You're right! I need to update the docs to reflect this change that happened a version or two ago.

Now the more important problem! It left us hanging huh? Leaving us with only:

```
Command exit status:
1
``` 

There should be a `logs` dir in `/home/marcellap/bactopia/work/a7/52dfddabf599066865ba4eaf067a98`. with some files )e.g. snippy.err etc...). Is there anything useful in those?

**Comment by marcelladane** [comment]
Hey, I checked the log file at A7, and is completely empty.
Should I check another one? maybe the step before....

For the other issue, you were correct, it was a repetition, I am sorry about that...

=)

**Comment by rpetit3** [comment]
No problem!

Are there any log files in `/home/marcellap/bactopia/work/a7/52dfddabf599066865ba4eaf067a98/call_variants`?

**Comment by marcelladane** [comment]
No, just the call_variants.version, snippy.err and snippy.out.

**Comment by rpetit3** [comment]
What is in `snippy.err`?

**Comment by marcelladane** [comment]
I will send it tomorrow for you, I just turned off the computer.
It's almost midnight here.

Tomorrow we keep going. :)

**Comment by rpetit3** [comment]
Sounds good! We'll get it figured out!

**Comment by marcelladane** [comment]
This is the content of the snippy.err: 

Value "15.8" invalid for option ram (number expected)
SYNOPSIS
  snippy 4.6.0 - fast bacterial variant calling from NGS reads
USAGE
  snippy [options] --outdir <dir> --ref <ref> --R1 <R1.fq.gz> --R2 <R2.fq.gz>
  snippy [options] --outdir <dir> --ref <ref> --ctgs <contigs.fa>
  snippy [options] --outdir <dir> --ref <ref> --bam <reads.bam>
GENERAL
  --help           This help
  --version        Print version and exit
  --citation       Print citation for referencing snippy
  --check          Check dependences are installed then exit (default OFF)
  --force          Force overwrite of existing output folder (default OFF)
  --quiet          No screen output (default OFF)
RESOURCES
  --cpus N         Maximum number of CPU cores to use (default '8')
  --ram N          Try and keep RAM under this many GB (default '8')
  --tmpdir F       Fast temporary storage eg. local SSD (default '/tmp')
INPUT
  --reference F    Reference genome. Supports FASTA, GenBank, EMBL (not GFF) (default '')
  --R1 F           Reads, paired-end R1 (left) (default '')
  --R2 F           Reads, paired-end R2 (right) (default '')
  --se F           Single-end reads (default '')
  --ctgs F         Don't have reads use these contigs (default '')
  --peil F         Reads, paired-end R1/R2 interleaved (default '')
  --bam F          Use this BAM file instead of aligning reads (default '')
  --targets F      Only call SNPs from this BED file (default '')
  --subsample n.n  Subsample FASTQ to this proportion (default '1')
OUTPUT
  --outdir F       Output folder (default '')
  --prefix F       Prefix for output files (default 'snps')
  --report         Produce report with visual alignment per variant (default OFF)
  --cleanup        Remove most files not needed for snippy-core (inc. BAMs!) (default OFF)
  --rgid F         Use this @RG ID: in the BAM header (default '')
  --unmapped       Keep unmapped reads in BAM and write FASTQ (default OFF)
PARAMETERS
  --mapqual N      Minimum read mapping quality to consider (default '60')
  --basequal N     Minimum base quality to consider (default '13')
  --mincov N       Minimum site depth to for calling alleles (default '10')
  --minfrac n.n    Minumum proportion for variant evidence (0=AUTO) (default '0')
  --minqual n.n    Minumum QUALITY in VCF column 6 (default '100')
  --maxsoft N      Maximum soft clipping to allow (default '10')
  --bwaopt F       Extra BWA MEM options, eg. -x pacbio (default '')
  --fbopt F        Extra Freebayes options, eg. --theta 1E-6 --read-snp-limit 2 (default '')
SOURCE
  https://github.com/tseemann/snippy - Torsten Seemann

**Comment by marcelladane** [comment]
I tried to run once more and noticed that the errors were related to:
SRX4563689 - GCF_003073655 error in call_variants
SRX4563686 - GCF_000016805 error in call_variants

That comes because I only get one subsp. in the reference genome.

**Comment by rpetit3** [comment]
Ah! found your issue! `Value "15.8" invalid for option ram (number expected)`

Does your computer only have 16GB of ram? I implemented a "check for max memory and adjust accordingly", apaarently it does not! I'll need to make it to where it rounds down to the nearest whole number (15.8 becomes 15).

To keep moving forward,  try adding `--snippy_ram  15` when you run bactopia.

**Comment by marcelladane** [comment]
Hello, sorry for taking a while to answer.
I tried what you advised and still doesn't work. I still get the same error.

**Comment by rpetit3** [comment]
Just to make sure, you tried with `--snippy_ram 15`?

**Comment by marcelladane** [comment]
Hey, yes, exactly. :)

**Comment by rpetit3** [comment]
Hmmm... did call_variants fail more than once?

**Comment by marcelladane** [comment]
Yes, a few times. I can do like so, if it helps, tomorrow i can run it again and send all errors that show up. Maybe it gives you some insight.

**Comment by marcelladane** [comment]
Here is the copy of the error I get when trying to run it:
executor >  local (37)
[bc/5dbebb] process > gather_fastqs (SRX4563634)                        [100%] 1 of 1 ✔
[59/88604e] process > fastq_status (1)                                  [100%] 1 of 1 ✔
[4d/ad88f6] process > estimate_genome_size (SRX4563634)                 [100%] 1 of 1 ✔
[08/3b29d1] process > qc_reads (SRX4563634)                             [100%] 1 of 1 ✔
[1c/64d7e8] process > qc_original_summary (SRX4563634)                  [100%] 1 of 1 ✔
[7e/885e50] process > qc_final_summary (SRX4563634)                     [100%] 1 of 1 ✔
[2c/45b588] process > assemble_genome (SRX4563634)                      [100%] 1 of 1 ✔
[29/eb7068] process > assembly_qc (SRX4563634 - quast)                  [100%] 2 of 2 ✔
[8d/8065fb] process > make_blastdb (SRX4563634)                         [100%] 1 of 1 ✔
[99/6bb68f] process > annotate_genome (SRX4563634)                      [100%] 1 of 1 ✔
[83/8d4210] process > count_31mers (SRX4563634)                         [100%] 1 of 1 ✔
[f6/cb1439] process > sequence_type (SRX4563634 - default - ariba)      [100%] 2 of 2 ✔
[32/7628d7] process > ariba_analysis (SRX4563634 - vfdb_core)           [100%] 2 of 2 ✔
[20/641292] process > minmer_sketch (SRX4563634)                        [100%] 1 of 1 ✔
[95/175afa] process > minmer_query (SRX4563634 - genbank-k31.json.gz)   [100%] 5 of 5 ✔
[37/79d97b] process > call_variants (SRX4563634 - GCF_000009645)        [100%] 4 of 4, failed: 4, retries: 3 ✘
[08/ce3497] process > download_references (SRX4563634 - 1 reference(s)) [100%] 1 of 1 ✔
[e6/b693d8] process > call_variants_auto (SRX4563634 - GCF_001717685)   [ 75%] 3 of 4, failed: 3, retries: 3
[06/9597ed] process > update_antimicrobial_resistance (1)               [100%] 1 of 1 ✔
[27/4c3ce8] process > antimicrobial_resistance (SRX4563634)             [100%] 1 of 1 ✔
[57/0973c6] process > plasmid_blast (SRX4563634)                        [100%] 1 of 1 ✔
[-        ] process > blast_genes                                       -
[c3/411501] process > blast_primers (SRX4563634)                        [100%] 1 of 1 ✔
[ac/d6fe70] process > blast_proteins (SRX4563634)                       [100%] 1 of 1 ✔
[40/8d9de9] process > mapping_query (SRX4563634})                       [100%] 1 of 1 ✔
[54/c4076b] NOTE: Process `call_variants (SRX4563634 - GCF_000009645)` terminated with an error exit status (1) -- Execution is retried (2)
[13/68756d] NOTE: Process `call_variants_auto (SRX4563634 - GCF_001717685)` terminated with an error exit status (1) -- Execution is retried (2)
[fc/8c918a] NOTE: Process `call_variants (SRX4563634 - GCF_000009645)` terminated with an error exit status (1) -- Execution is retried (3)
[90/34a015] NOTE: Process `call_variants_auto (SRX4563634 - GCF_001717685)` terminated with an error exit status (1) -- Execution is retried (3)

And when I look into the history, as I said, although trying to set snippy, it still trying to use 15.8.

**Comment by rpetit3** [comment]
Alright, I pushed a commit (https://github.com/bactopia/bactopia/commit/05a94b6b47cadc9dc0574739d8ebcb1765b8c8e9) that should hopefully fix this. It will be in the next version update, which should hopefully be soon.

**Comment by rpetit3** [comment]
@marcelladane v1.5.0 is now available on Bioconda, so I am going to close this for now. Please let me know if your problem persists! I would like to help get this figured out for you. Thank you very much for your feedback!

**Comment by marcelladane** [comment]
Hey, sadly the new version still gives the same error when calling variants. 
But now our server is up so I am using it and had no issues there. 
Just so you know.

=)

**Comment by rpetit3** [comment]
Glad you were able to use it on your server! 

That's a bummer on your local machine, I'll dig into and see if it was a weird "have to do this on WSL" situation. I tested the memory issue on OSX and Linux, but not WSL.
