### ISSUE TITLE
[bug] amrfinder version in Conda environments need update to match database

### ISSUE THREAD

**Issue by spleonard1** [bactopia/bactopia#247]
**Description**
A description of the bug you are experiencing.
Running through the bactopia tutorial on my Mac, the workflow errors out at the amrfinder step with this message: 

WARN: Task runtime metrics are not reported when using macOS without a container engine
[99/e7e69d] NOTE: Process `antimicrobial_resistance (SRX4563634)` terminated with an error exit status (1) -- Execution is retried (1)
[9f/557fbd] NOTE: Process `antimicrobial_resistance (SRX4563634)` terminated with an error exit status (1) -- Execution is retried (2)
[c3/25610a] NOTE: Process `antimicrobial_resistance (SRX4563634)` terminated with an error exit status (1) -- Execution is retried (3)
Error executing process > 'antimicrobial_resistance (SRX4563634)'

Caused by:
  Process `antimicrobial_resistance (SRX4563634)` terminated with an error exit status (1)

Command executed [/Users/seanleonard/miniconda3/envs/bactopia/share/bactopia-1.7.x/templates/antimicrobial_resistance.sh]

  #!/bin/bash
  set -e
  set -u
  
  LOG_DIR="logs/antimicrobial_resistance"
  mkdir -p ${LOG_DIR}
  
  # Print captured STDERR incase of exit
  function print_stderr {
      cat .command.err 1>&2
      ls ${LOG_DIR}/ | grep ".err" | xargs -I {} cat ${LOG_DIR}/{} 1>&2
  }
  trap print_stderr EXIT
  
  echo "# Timestamp" > ${LOG_DIR}/antimicrobial_resistance.versions
  date --iso-8601=seconds >> ${LOG_DIR}/antimicrobial_resistance.versions
  
  # Verify AWS files were staged
  if [[ ! -L "SRX4563634.ffn " ]]; then
      check-staging.py --fq1 SRX4563634.ffn --fq2 SRX4563634.faa --extra amrfinderdb.tar.gz
  fi
  
  if [[ false == "true" ]]; then
      gzip -cd SRX4563634.ffn > SRX4563634.ffn
      gzip -cd SRX4563634.faa > SRX4563634.faa
  fi
  
  tar -xzvf amrfinderdb.tar.gz
  mkdir antimicrobial-resistance
  
  # amrfinder Version
  echo "# amrfinder Version" >> ${LOG_DIR}/antimicrobial_resistance.versions
  amrfinder --version >> ${LOG_DIR}/antimicrobial_resistance.versions 2>&1
  amrfinder -n SRX4563634.ffn \
            -d amrfinderdb/ \
            -o antimicrobial-resistance/SRX4563634-gene-report.txt \
            --ident_min -1 \
            --coverage_min 0.5 \
            --translation_table 11 \
            --threads 2    > ${LOG_DIR}/amrfinder-gene.out 2> ${LOG_DIR}/amrfinder-gene.err
  
  amrfinder -p SRX4563634.faa \
            -d amrfinderdb/ \
            -o antimicrobial-resistance/SRX4563634-protein-report.txt \
            --ident_min -1 \
            --coverage_min 0.5 \
            --translation_table 11 \
            --threads 2    > ${LOG_DIR}/amrfinder-protein.out 2> ${LOG_DIR}/amrfinder-protein.err
  
  if [[ false == "true" ]]; then
      rm SRX4563634.faa SRX4563634.ffn
  fi
  
  if [ "false" == "false" ]; then 
      cp .command.err ${LOG_DIR}/antimicrobial_resistance.err
      cp .command.out ${LOG_DIR}/antimicrobial_resistance.out
      cp .command.sh ${LOG_DIR}/antimicrobial_resistance.sh || :
      cp .command.trace ${LOG_DIR}/antimicrobial_resistance.trace || :
  else
      rm -rf ${LOG_DIR}/
  fi

Command exit status:
  1

Command output:
  (empty)

Command error:
  x amrfinderdb/AMRProt-susceptible.tab
  x amrfinderdb/AMR_CDS.ndb
  x amrfinderdb/taxgroup.tab
  x amrfinderdb/AMR_DNA-Campylobacter.ndb
  x amrfinderdb/AMR_DNA-Campylobacter.nhr
  x amrfinderdb/AMR_DNA-Salmonella.not
  x amrfinderdb/AMR_DNA-Clostridioides_difficile.nsq
  x amrfinderdb/AMR_DNA-Neisseria.not
  x amrfinderdb/AMR_DNA-Escherichia
  x amrfinderdb/AMR_DNA-Streptococcus_pneumoniae.nin
  x amrfinderdb/AMR_DNA-Staphylococcus_aureus.nto
  x amrfinderdb/AMR_CDS
  x amrfinderdb/AMR_DNA-Staphylococcus_aureus.ntf
  x amrfinderdb/AMR_DNA-Escherichia.nsq
  x amrfinderdb/AMR_CDS.nto
  x amrfinderdb/AMR_DNA-Staphylococcus_aureus.tab
  x amrfinderdb/AMR_CDS.ntf
  x amrfinderdb/AMR.LIB.h3p
  x amrfinderdb/AMR.LIB.h3m
  x amrfinderdb/version.txt
  x amrfinderdb/AMR_DNA-Salmonella.ndb
  x amrfinderdb/AMR_DNA-Neisseria.ndb
  x amrfinderdb/AMRProt.psq
  x amrfinderdb/AMR_DNA-Campylobacter.not
  x amrfinderdb/AMR_DNA-Salmonella.nhr
  x amrfinderdb/AMR_DNA-Neisseria.nhr
  x amrfinderdb/AMR_DNA-Staphylococcus_aureus.nhr
  x amrfinderdb/AMR_CDS.not
  x amrfinderdb/AMR_DNA-Staphylococcus_aureus.ndb
  x amrfinderdb/AMR_DNA-Streptococcus_pneumoniae.nsq
  x amrfinderdb/AMR_DNA-Neisseria.tab
  x amrfinderdb/AMR_DNA-Campylobacter.ntf
  x amrfinderdb/AMR_DNA-Campylobacter.nto
  x amrfinderdb/AMR_DNA-Salmonella.tab
  x amrfinderdb/AMR_DNA-Clostridioides_difficile.nin
  Running: amrfinder -n SRX4563634.ffn -d amrfinderdb/ -o antimicrobial-resistance/SRX4563634-gene-report.txt --ident_min -1 --coverage_min 0.5 --translation_table 11 --threads 2
  Software directory: '/Users/seanleonard/miniconda3/envs/bactopia/share/bactopia-1.7.x/conda/envs/antimicrobial_resistance-1.7.x/bin/'
  Software version: 3.10.1
  Database directory: 'amrfinderdb'
  Database version: 2021-09-30.1
  
  *** ERROR ***
  Database requires sofware version at least 3.10.16
  To download the latest version to the default directory run: amrfinder -u
  
  HOSTNAME: ?
  SHELL: /bin/bash
  PWD: /Users/seanleonard/Dropbox/learning/bactopia/work/bactopia/55/d47a6dcdd4697de149ceea3b78097e
  Progam name:  amrfinder
  Command line: amrfinder -n SRX4563634.ffn -d amrfinderdb/ -o antimicrobial-resistance/SRX4563634-gene-report.txt --ident_min -1 --coverage_min 0.5 --translation_table 11 --threads 2

Work dir:
  /Users/seanleonard/Dropbox/learning/bactopia/work/bactopia/55/d47a6dcdd4697de149ceea3b78097e

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line

 
**Steps to Reproduce**
```
bactopia ...
bactopia tools ...
!!ERROR!!
```

**Expected Behavior**
A description of what is expected to happen. 

**Execution Environment**

- Bactopia Version: [output from `bactopia version`]
- OS: [e.g. Mac, Ubuntu, etc...]
- Mac
- Environment: [e.g. conda, cluster, container, etc...]
- local (using Conda)

**Additional Information**
Any other information you think might be helpful in squashing this bug.
Tried to manually update amrfinder in conda environment. version 3.10.16 is available from conda, but conflicts with other parts of amrfinder environment

(antimicrobial_resistance-1.7.x)
 => conda install -c bioconda ncbi-amrfinderplus=3.10.16
UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package zlib conflicts for:
ncbi-amrfinderplus=3.10.16 -> blast[version='>=2.9'] -> zlib[version='>=1.2.11,<1.3.0a0']
python=3.9.2 -> zlib[version='>=1.2.11,<1.3.0a0']

Package libcxx conflicts for:
python=3.9.2 -> libffi[version='>=3.3,<3.4.0a0'] -> libcxx[version='>=11.0.0|>=4.0.1']
python=3.9.2 -> libcxx[version='>=10.0.0|>=11.0.1']

**Comment by rpetit3** [comment]
Hi @spleonard1 

I've release v2 (https://github.com/bactopia/bactopia/releases/tag/v2.0.0) and this should now be fixed. It's likely you'll need to rebuild the dataset for it to work. Please feel free to reopen if not.

Cheers!
Robert

**Comment by hamid89** [comment]
the issue is still there..... Running: amrfinder -u
Software directory: '/home/hamid/miniconda3/envs/bakcharak/bin/'
Software version: 3.10.5
Running: /home/hamid/miniconda3/envs/bakcharak/bin/amrfinder_update -d /home/hamid/miniconda3/envs/bakcharak/share/amrfinderplus/data
Looking up databases at https://ftp.ncbi.nlm.nih.gov/pathogen/Antimicrobial_resistance/AMRFinderPlus/database/
WARNING: '/home/hamid/miniconda3/envs/bakcharak/share/amrfinderplus/data/2021-12-21.1/' contains the latest version: 2021-12-21.1
Skipping update, use amrfinder --force_update to overwrite the existing database

Database directory: '/home/hamid/miniconda3/envs/bakcharak/share/amrfinderplus/data/2021-12-21.1'
Database version: 2021-12-21.1

*** ERROR ***
Database requires sofware version at least 3.10.16
To download the latest version to the default directory run: amrfinder -u

**Comment by rpetit3** [comment]
Hi @hamid89 

What version of Bactopia are you using?
