### ISSUE TITLE
BACTOPIATOOLS:PANGENOME:SCOARY` declares 2 input channels but 3 were specified

### ISSUE THREAD

**Issue by brross60** [bactopia/bactopia#278]
**Description**
SCOARY failing = BACTOPIATOOLS:PANGENOME:SCOARY` declares 2 input channels but 3 were specified. 
Trait.csv has genome in column 1 and trait as 0 or 1 in column 2.

**Steps to Reproduce**
bactopia --wf pangenome --bactopia /home/xxx/Desktop/Bactopia/ --include /home/xxx/Desktop/Bactopia/geneomes.txt --condadir /home/xxx/Desktop/Bactopia/ --max_time 1000 --traits traits.csv
N E X T F L O W  ~  version 21.10.6
Launching `/opt/anaconda/envs/bactopia/share/bactopia-2.0.x/main.nf` [infallible_varahamihira] - revision: a8b81a1850

--------------------------------------------------------------------
   _                _              _         _              _              
  | |__   __ _  ___| |_ ___  _ __ (_) __ _  | |_ ___   ___ | |___          
  | '_ \ / _` |/ __| __/ _ \| '_ \| |/ _` | | __/ _ \ / _ \| / __|    
  | |_) | (_| | (__| || (_) | |_) | | (_| | | || (_) | (_) | \__ \        
  |_.__/ \__,_|\___|\__\___/| .__/|_|\__,_|  \__\___/ \___/|_|___/ 
                            |_|                                            
  bactopia tools pangenome v2.0.1
  Pangenome analysis with optional core-genome phylogeny 
--------------------------------------------------------------------
Core Nextflow options
  runName          : infallible_varahamihira
  launchDir        : /home/xxx/Desktop/Bactopia
  workDir          : /home/xxx/Desktop/Bactopia/work/pangenome
  projectDir       : /opt/anaconda/envs/bactopia/share/bactopia-2.0.x
  userName         : xx
  profile          : standard
  configFiles      : /opt/anaconda/envs/bactopia/share/bactopia-2.0.x/nextflow.config

Required Parameters
  bactopia         : /home/xxx/Desktop/Bactopia/

Filtering Parameters
  include          : /home/xxx/Desktop/Bactopia/geneomes.txt

Scoary Parameters
  traits           : traits.csv

Optional Parameters
  outdir           : /home/xxx/Desktop/Bactopia/
  run_name         : pangenome

Max Job Request Parameters
  max_time         : 1000

Nextflow Profile Parameters
  condadir         : /home/xxx/Desktop/Bactopia/
  singularity_cache: /home/xxx/.bactopia/singularity

Helpful Parameters
  wf               : pangenome

!! Only displaying parameters that differ from the pipeline defaults !!
--------------------------------------------------------------------
If you use bactopia for your analysis please cite:

* Bactopia
  https://doi.org/10.1128/mSystems.00190-20

* The nf-core framework
  https://doi.org/10.1038/s41587-020-0439-x

* Software dependencies
  https://bactopia.github.io/acknowledgements/
--------------------------------------------------------------------
WARN: 
WARN: Conda Disclaimer
WARN: 
WARN: If you have access to Docker or Singularity, please consider
WARN: running Bactopia using containers. The containers are less
WARN: susceptible to Conda environment related issues (e.g. version
WARN: conflicts) and errors caused by creation of conda environments
WARN: in parallel (use '--max_cpus 1' to over come this error).
WARN: 
WARN: To use containers, you can use the profile parameter
WARN:     Docker: -profile docker
WARN:     Singularity: -profile singularity
WARN: 
--------------------------------------------------------------------

Each task will use 4 CPUs out of the available 20 CPUs. At most 
5 task(s) will be run at a time, this can affect the efficiency 
of Bactopia. You can use the '-qs' parameter to alter the number of 
tasks to run at a time (e.g. '-qs 2', means only 2 tasks or a maximum 
of 8 CPUs will be used at once)

Including 56 samples for analysis
Found 56 samples to process

If this looks wrong, now's your chance to back out (CTRL+C 3 times).
Sleeping for 5 seconds...
--------------------------------------------------------------------
[-        ] process > BACTOPIATOOLS:PROKKA:PROKKA... -
Process `BACTOPIATOOLS:PANGENOME:SCOARY` declares 2 input channels but 3 were specified

 -- Check script '/opt/anaconda/envs/bactopia/share/bactopia-2.0.x/./workflows/../subworkflows/local/pangenome/main.nf' at line: 49 or see '.nextflow.log' file for more details

**Expected Behavior**
Gene association with presence or absence of a trait (0/1).

**Execution Environment**
- Bactopia Version: v2.0.1
- OS: Ubuntu
- Environment: conda

**Additional Information**
When I went into the pirate file the presence/absence.csv was empty. This may be the issue. Alternatively, should i be using roary with SCOARY?

**Comment by rpetit3** [comment]
Great! I was expecting his to be broken, and was waiting for someone with a good example of a traits file to give it a go. (I've never actually used Scoary)

You should be able to use either PIRATE or Roary. Although an empty presence/absence.csv file is no good. I'm going to fix the Scoary part, then if you want to try Roary that would be helpful.

**Comment by brross60** [comment]
Oh cool lol. I already tried roary and got this error...


bactopia --wf pangenome --bactopia /home/xxx/Desktop/Bactopia/ --include /home/xxx/Desktop/Bactopia/Emory_geneomes.txt --condadir /home/xxx/Desktop/Bactopia/ --max_time 1000 --traits traits.csv --use_roary
N E X T F L O W  ~  version 21.10.6
Launching `/opt/anaconda/envs/bactopia/share/bactopia-2.0.x/main.nf` [prickly_gutenberg] - revision: a8b81a1850


--------------------------------------------------------------------
   _                _              _         _              _              
  | |__   __ _  ___| |_ ___  _ __ (_) __ _  | |_ ___   ___ | |___          
  | '_ \ / _` |/ __| __/ _ \| '_ \| |/ _` | | __/ _ \ / _ \| / __|    
  | |_) | (_| | (__| || (_) | |_) | | (_| | | || (_) | (_) | \__ \        
  |_.__/ \__,_|\___|\__\___/| .__/|_|\__,_|  \__\___/ \___/|_|___/ 
                            |_|                                            
  bactopia tools pangenome v2.0.1
  Pangenome analysis with optional core-genome phylogeny 
--------------------------------------------------------------------
Core Nextflow options
  runName          : prickly_gutenberg
  launchDir        : /home/xxx/Desktop/Bactopia
  workDir          : /home/xxx/Desktop/Bactopia/work/pangenome
  projectDir       : /opt/anaconda/envs/bactopia/share/bactopia-2.0.x
  userName         : xxx
  profile          : standard
  configFiles      : /opt/anaconda/envs/bactopia/share/bactopia-2.0.x/nextflow.config

Required Parameters
  bactopia         : /home/xxx/Desktop/Bactopia/

Filtering Parameters
  include          : /home/xxx/Desktop/Bactopia/geneomes.txt

Roary Parameters
  use_roary        : true

Scoary Parameters
  traits           : traits.csv

Optional Parameters
  outdir           : /home/xxx/Desktop/Bactopia/
  run_name         : pangenome

Max Job Request Parameters
  max_time         : 1000

Nextflow Profile Parameters
  condadir         : /home/xxx/Desktop/Bactopia/
  singularity_cache: /home/xxx/.bactopia/singularity

Helpful Parameters
  wf               : pangenome

!! Only displaying parameters that differ from the pipeline defaults !!
--------------------------------------------------------------------
If you use bactopia for your analysis please cite:

* Bactopia
  https://doi.org/10.1128/mSystems.00190-20

* The nf-core framework
  https://doi.org/10.1038/s41587-020-0439-x

* Software dependencies
  https://bactopia.github.io/acknowledgements/
--------------------------------------------------------------------
WARN: 
WARN: Conda Disclaimer
WARN: 
WARN: If you have access to Docker or Singularity, please consider
WARN: running Bactopia using containers. The containers are less
WARN: susceptible to Conda environment related issues (e.g. version
WARN: conflicts) and errors caused by creation of conda environments
WARN: in parallel (use '--max_cpus 1' to over come this error).
WARN: 
WARN: To use containers, you can use the profile parameter
WARN:     Docker: -profile docker
WARN:     Singularity: -profile singularity
WARN: 
--------------------------------------------------------------------
argument type mismatch

 -- Check script '/opt/anaconda/envs/bactopia/share/bactopia-2.0.x/./workflows/../subworkflows/local/pangenome/../roary/main.nf' at line: 5 or see '.nextflow.log' file for more details



nextlof.log
Feb-08 15:33:33.786 [main] DEBUG nextflow.Session - Session aborted -- Cause: argument type mismatch
Feb-08 15:33:33.803 [main] ERROR nextflow.cli.Launcher - argument type mismatch
java.lang.IllegalArgumentException: argument type mismatch
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at nextflow.script.FunctionDef.invoke_a(FunctionDef.groovy:57)
        at nextflow.script.ComponentDef.invoke_o(ComponentDef.groovy:41)
        at nextflow.script.WorkflowBinding.invokeMethod(WorkflowBinding.groovy:94)
        at groovy.lang.GroovyObject$invokeMethod.call(Unknown Source)
        at nextflow.script.BaseScript.invokeMethod(BaseScript.groovy:156)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(Pat org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:194)
        at Script_e8f4e526.runScript(Script_e8f4e526:5)
        at nextflow.script.BaseScript.runDsl2(BaseScript.groovy:169)
        at nextflow.script.BaseScript.run(BaseScript.groovy:200)
        at nextflow.script.ScriptParser.runScript(ScriptParser.groovy:221)
        at nextflow.script.ScriptParser.runScript(ScriptParser.groovy:207)
        at nextflow.script.ScriptParser.runScript(ScriptParser.groovy:201)
        at nextflow.script.IncludeDef.memoizedMethodPriv$loadModule0PathMapSession(IncludeDef.groovy:142)
        at nextflow.script.IncludeDef.access$0(IncludeDef.groovy)
        at nextflow.script.IncludeDef$__clinit__closure1.doCall(IncludeDef.groovy)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
        at groovy.lang.Closure.call(Closure.java:412)
ogoMetaClassSite.java:68)
at org.codehaus.groovy.runtime.memoize.Memoize$MemoizeFunction.lambda$call$0(Memoize.java:137)
        at org.codehaus.groovy.runtime.memoize.ConcurrentCommonCache.getAndPut(ConcurrentCommonCache.java:137)
        at org.codehaus.groovy.runtime.memoize.ConcurrentCommonCache.getAndPut(ConcurrentCommonCache.java:113)
        at org.codehaus.groovy.runtime.memoize.Memoize$MemoizeFunction.call(Memoize.java:136)
        at nextflow.script.IncludeDef.loadModule0(IncludeDef.groovy)
        at nextflow.script.IncludeDef.load0(IncludeDef.groovy:114)
        at nextflow.script.IncludeDef$load0$1.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
        at Script_4deb3a73.runScript(Script_4deb3a73:5)
        at nextflow.script.BaseScript.runDsl2(BaseScript.groovy:169)
        at nextflow.script.BaseScript.run(BaseScript.groovy:200)
        at nextflow.script.ScriptParser.runScript(ScriptParser.groovy:221)
        at nextflow.script.ScriptParser.runScript(ScriptParser.groovy:207)
        at nextflow.script.ScriptParser.runScript(ScriptParser.groovy:201)
        at nextflow.script.IncludeDef.memoizedMethodPriv$loadModule0PathMapSession(IncludeDef.groovy:142)
        at nextflow.script.IncludeDef.access$0(IncludeDef.groovy)
        at nextflow.script.IncludeDef$__clinit__closure1.doCall(IncludeDef.groovy)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
.....

**Comment by rpetit3** [comment]
Cool, thank you for finding this.

I've fixed the PIRATE gene_presence_absence.csv outputs. I had the syntax wrong. I've also fixed Scoary. 

Going to look into this Roary error now

**Comment by rpetit3** [comment]
Ok think I got these fixed in https://github.com/bactopia/bactopia/commit/bc7eef4608512e43b7767c8bf0a9dcfca1767f14 it'll be in the next version.

If you like to give these changes a try now, I have a latest build on my personal anaconda channel.

```
mamba create -n test-bactopia -c rpetit3 -c conda-forge -c bioconda bactopia
```

**Comment by brross60** [comment]
Awesome, working on getting this downloaded but have administrative walls to get through. I'll let you know how it works.

**Comment by brross60** [comment]
Ok so Roary works now, Whoo hoo! Scoary still does not work because it cant find the traits file. 

Error:
[-        ] process > BACTOPIATOOLS:PROKKA:PROKKA_MODULE                   -
[a3/1e7ac3] process > BACTOPIATOOLS:PANGENOME:PG_TOOL:ROARY_MODULE (roary) [100%] 1 of 1 ✔
[-        ] process > BACTOPIATOOLS:PANGENOME:SNPDISTS                     -
[-        ] process > BACTOPIATOOLS:PANGENOME:CLONALFRAMEML:IQTREE         -
[-        ] process > BACTOPIATOOLS:PANGENOME:CLONALFRAMEML:CLONALFRAME    -
[-        ] process > BACTOPIATOOLS:PANGENOME:FINAL_TREE:IQTREE_MODULE     -
[a8/17da8a] process > BACTOPIATOOLS:PANGENOME:SCOARY:SCOARY_MODULE (roary) [100%] 4 of 4, failed: 4, retries: 3 ✘
[-        ] process > BACTOPIATOOLS:CUSTOM_DUMPSOFTWAREVERSIONS            -
[a9/e90030] NOTE: Process `BACTOPIATOOLS:PANGENOME:SCOARY:SCOARY_MODULE (roary)` terminated with an error exit status (1) -- Execution is retried (1)
[99/d35a4d] NOTE: Process `BACTOPIATOOLS:PANGENOME:SCOARY:SCOARY_MODULE (roary)` terminated with an error exit status (1) -- Execution is retried (2)
[74/c495f9] NOTE: Process `BACTOPIATOOLS:PANGENOME:SCOARY:SCOARY_MODULE (roary)` terminated with an error exit status (1) -- Execution is retried (3)
Error executing process > 'BACTOPIATOOLS:PANGENOME:SCOARY:SCOARY_MODULE (roary)'

Caused by:
  Process `BACTOPIATOOLS:PANGENOME:SCOARY:SCOARY_MODULE (roary)` terminated with an error exit status (1)

Command executed:

  scoary \
      --p_value_cutoff 0.05 --correction I --start_col 15 \
      --no-time \
      --threads 4 \
      --traits traits.csv \
      --genes gene_presence_absence.csv
  
  cat <<-END_VERSIONS > versions.yml
  "BACTOPIATOOLS:PANGENOME:SCOARY:SCOARY_MODULE":
      scoary: $( scoary --version 2>&1 )
  END_VERSIONS

Command exit status:
  1

Command output:
  ==== Scoary started ====
  Command: /home/xxx/Desktop/Bactopia/scoary/bin/scoary --p_value_cutoff 0.05 --correction I --start_col 15 --no-time --threads 4 --traits traits.csv --genes gene_presence_absence.csv
  CRITICAL:
  Traceback (most recent call last):
    File "/home/xxx/Desktop/Bactopia/scoary/lib/python3.6/site-packages/scoary/methods.py", line 132, in main
      sys.exit("Could not find the traits file: %s" % args.traits)
  SystemExit: Could not find the traits file: traits.csv

Command error:
  Could not find the traits file: traits.csv

Work dir:
  /home/xxx/Desktop/Bactopia/work/a8/17da8ae4c480ba54c0ba8738f45839

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

**Comment by rpetit3** [comment]
Thanks for the update, what was the command used at runtime?

**Comment by brross60** [comment]
```

/home/xxx/Desktop/Bactopia/work/a8/17da8ae4c480ba54c0ba8738f45839
traits.csv
gene-presence_abscense.csv 
scoary.log
```

The traits file it says it broken. Opened in a text editor its empty
here is the log contents:
0```
2/16/2022 05:19:50 PM    ==== Scoary started ====
02/16/2022 05:19:50 PM    Command: /home/xxx/Desktop/Bactopia/scoary/bin/scoary --p_value_cutoff 0.05 --correction I --start_col 15 --no-time --threads 4 --traits traits.csv --genes gene_presence_absence.csv
02/16/2022 05:19:50 PM    CRITICAL:
Traceback (most recent call last):
  File "/home/xxx/Desktop/Bactopia/scoary/lib/python3.6/site-packages/scoary/methods.py", line 132, in main
    sys.exit("Could not find the traits file: %s" % args.traits)
SystemExit: Could not find the traits file: traits.csv
```

**Comment by rpetit3** [comment]
Ok I'm going to look into this further to see if I can replicate

**Comment by rpetit3** [comment]
Hmmm, I wasn't able to reproduce on my end.

My traits file looks like this: 

```
,Tetracycline_resistance,Bogus_trait
GCF_000292685,0,0
GCF_000298385,0,1
GCF_002849995,0,1
GCF_000300075,1,0
GCF_902713755,0,NA
```

**Comment by brross60** [comment]
Woohoo I got it to work. I think the traits file got messed up in the transfer from mac to linux. Got some cool results too. Have roary + --species running now but as soon as it is done ill try pirate to see how the presence absence file comes out.

**Comment by rpetit3** [comment]
That's super exciting! Glad you were able to get it figured out.

I'm going to be releasing v2.0.2 today or tomorrow, which will include fixes to the bugs you found. Thank you so much for bringing it up here!

**Comment by rpetit3** [comment]
I've released v2.0.2 (https://github.com/bactopia/bactopia/releases/tag/v2.0.2) which includes this fix. 

Going to go ahead and close this issue! Thanks again for all the help!

**Comment by rpetit3** [comment]
If you have a moment, could you take a few minutes to fill out a [Bactopia Usage Survey](https://forms.gle/PTgUxEBwCsCdbQjr7)? It really helps me direct the direction of Bactopia's development! Thanks!

**Comment by brross60** [comment]
Awesome, thanks again for you help!!!. Not a problem!
